import glob
from datetime import datetime

now = datetime.now()
outFilePath = "Makefile"
templatePath = "MakefileTemplate"
includeFile = ""
includeDirectory = ""

for filename in glob.iglob('Core/**/*.c', recursive=True):
    includeFile = includeFile + filename + " \\\n"

for filename in glob.iglob('Drivers/**/*.c', recursive=True):
    includeFile = includeFile + filename + " \\\n"

for filename in glob.iglob('FileX/**/*.c', recursive=True):
    includeFile = includeFile + filename + " \\\n"
    
for filename in glob.iglob('Middlewares/**/*.c', recursive=True):
    includeFile = includeFile + filename + " \\\n"
    
for filename in glob.iglob('TouchGFX/**/*.c', recursive=True):
    includeFile = includeFile + filename + " \\\n"
    
for filename in glob.iglob('USBX/**/*.c', recursive=True):
    includeFile = includeFile + filename + " \\\n"
    
for filename in glob.iglob('User/**/*.c', recursive=True):
    includeFile = includeFile + filename + " \\\n"
    
    

for dirName in glob.iglob('Core/**/', recursive=True):
    includeDirectory = includeDirectory + "-I" + dirName[:-1] + " \\\n"

for dirName in glob.iglob('Drivers/**/', recursive=True):
    includeDirectory = includeDirectory + "-I" + dirName[:-1] + " \\\n"

for dirName in glob.iglob('FileX/**/', recursive=True):
    includeDirectory = includeDirectory + "-I" + dirName[:-1] + " \\\n"

for dirName in glob.iglob('Middlewares/**/', recursive=True):
    includeDirectory = includeDirectory + "-I" + dirName[:-1] + " \\\n"

for dirName in glob.iglob('TouchGFX/**/', recursive=True):
    includeDirectory = includeDirectory + "-I" + dirName[:-1] + " \\\n"

for dirName in glob.iglob('USBX/**/', recursive=True):
    includeDirectory = includeDirectory + "-I" + dirName[:-1] + " \\\n"

for dirName in glob.iglob('User/**/', recursive=True):
    includeDirectory = includeDirectory + "-I" + dirName[:-1] + " \\\n"

# print(includeFile)
# print(includeDirectory)

readfile = open(templatePath, 'r')
outfile = open(outFilePath, 'w')
header = 0
replacePart = 0
replaceHeader = 0

print("Start generate Makefile script")
outfile.write("#############################################################")
outfile.write("#############################################################\n")
outfile.write("# File automatically-generated by script genMakeFromTemplate.py @ ")
outfile.write(now.strftime("%H:%M:%S %d/%m/%Y\n"))
outfile.write("# Tested with generate Makefile version 3.16.0 \n")
outfile.write("# Template from STM32 ")

for line in readfile:
    header += 1
    if (header < 3) and (line.find("[projectgenerator]") != -1):
        buf = line[line.find("[projectgenerator]"):]
        outfile.write(buf)
        outfile.write("#############################################################")
        outfile.write("#############################################################\n")
        replaceHeader = 1

    if (header == 3) and (replaceHeader == 0):
        outfile.write("Makefile auto generate \n")
        outfile.write("#############################################################")
        outfile.write("#############################################################\n")

    if header > 3:
        if line.startswith("C_SOURCES ="):
            outfile.write(line)
            outfile.write(includeFile)
            outfile.write("\n")
            replacePart = 1

        if line.startswith("C_INCLUDES ="):
            outfile.write(line)
            outfile.write(includeDirectory)
            outfile.write("\n")
            replacePart = 1

        if replacePart == 1:
            if line.isspace():
                replacePart = 0
        elif line.startswith("LDSCRIPT ="):
            outfile.write(line[0:11] + "./" + line[11:])
        else:
            outfile.write(line)

outfile.flush()
print("Script ended")
